// Bills Data - Civil Rights Legislation Tracker for Chinese Americans
// Focus: Civil Rights Impact on Individuals
// Tier 1: affects lawful permanent residents or US citizens (displayed)
// Tier 2: affects visa holders but not residents (displayed, labeled)
// Tier 3: affects companies/foreign entities only (monitoring database, not displayed)
// Last updated: 2026-08-18

const billsData = [
  // ENACTED BILLS - Tier 2: affect visa holders, not residents
  {
    "id": "fl/government-SB 264",
    "state": "FL",
    "stateName": "Florida",
    "billNumber": "SB 264",
    "title": "Foreign Land Ownership Restrictions",
    "tier": 2,
    "status": "ENACTED",
    "session": "2023 (ch. 2023-33)",
    "category": "property",
    "target": "Persons domiciled in China who are not US citizens or lawful permanent residents; PRC government, CCP, China-based entities",
    "restrictions": "Property restrictions",
    "penalties": "Civil penalties, forfeiture, 3rd-degree felony",
    "summary": "Prohibits the PRC government, the Chinese Communist Party, China-based entities, and persons domiciled in the PRC who are not US citizens or lawful permanent residents from owning or acquiring real property in Florida (Fla. Stat. §692.204). US citizens and lawful permanent residents are exempt, and covered individuals may purchase one residential property of up to 2 acres located more than 5 miles from a military installation if they hold a qualifying visa or asylum status.",
    "civilRightsImpact": "Restricts property ownership based on nationality and residence: US citizens and lawful permanent residents are exempt, but non-citizen, non-permanent-resident persons domiciled in China — including Chinese nationals on non-tourist visas — face restrictions that do not apply to nationals of other countries. Existing owners must register their property and face a $1,000-per-day civil penalty for late registration; violations can lead to civil forfeiture actions and third-degree felony charges. The law is being challenged in federal litigation (Shen v. Simpson, 11th Cir., Nov. 2025).",
    "keyProvisions": [
      "Prohibits covered PRC-linked persons and entities from acquiring real property (Fla. Stat. §692.204)",
      "Exempts US citizens and lawful permanent residents",
      "Exception: one residential parcel up to 2 acres, more than 5 miles from military installations, for qualifying visa/asylum holders",
      "Registration requirement for property acquired before July 1, 2023 ($1,000/day late penalty)",
      "Civil forfeiture actions by the Department of Commerce; violations are a 3rd-degree felony",
      "Pending litigation: Shen v. Simpson (11th Cir.)"
    ],
    "url": "https://www.flsenate.gov/Session/Bill/2023/264",
    "officialUrl": "https://www.flsenate.gov/Session/Bill/2023/264/BillText/er/PDF",
    "introducedDate": "2023-01-09",
    "lastUpdated": "2025-11-04"
  },
  {
    "id": "tx/government-SB 17",
    "state": "TX",
    "stateName": "Texas",
    "billNumber": "SB 17",
    "title": "Prohibit purchase of real property by certain foreign nationals/entities",
    "tier": 2,
    "status": "ENACTED (Sept 1, 2025)",
    "session": "89th Legislature",
    "category": "property",
    "target": "Nationals of designated countries (China, Russia, Iran, North Korea) who are not US citizens or lawful permanent residents",
    "restrictions": "Property restrictions",
    "penalties": "Criminal offense and civil penalty",
    "summary": "Prohibits foreign individuals and entities associated with 'designated countries' — currently China, Russia, Iran, and North Korea — from purchasing or acquiring real property in Texas (Tex. Prop. Code §5.251 et seq.). Exempts US citizens and lawful permanent residents, entities owned exclusively by them, and leaseholds under 100 years. Individuals lawfully present in the US may still acquire a primary residence homestead.",
    "civilRightsImpact": "Applies to Chinese nationals who are not US citizens or lawful permanent residents — including student and work visa holders — who are domiciled in China, are Chinese citizens without permanent-resident status in another country, or are unlawfully present in the US. Lawful permanent residents and US citizens are explicitly exempt. Violations create a criminal offense and a civil penalty. The law is being challenged in federal court (lawsuit filed by the Chinese American Legal Defense Alliance, July 2025).",
    "keyProvisions": [
      "Defines 'designated country' as countries identified by the US Director of National Intelligence as national security risks (currently China, Russia, Iran, North Korea) or designated by the governor",
      "Prohibits covered individuals and entities from purchasing or acquiring real property in Texas",
      "Exempts US citizens, lawful permanent residents, and entities owned by them",
      "Residence homestead exception for individuals lawfully present in the US",
      "Criminal offense and civil penalty for violations",
      "Federal lawsuit filed July 3, 2025"
    ],
    "url": "https://capitol.texas.gov/BillLookup/History.aspx?LegSess=89R&Bill=SB17",
    "officialUrl": "https://capitol.texas.gov/tlodocs/89R/billtext/html/SB00017F.htm",
    "introducedDate": "2025-01-09",
    "lastUpdated": "2025-09-01"
  },
  {
    "id": "fl/education-HB 1279",
    "state": "FL",
    "stateName": "Florida",
    "billNumber": "HB 1279",
    "title": "Noncitizen and nonresident student enrollment limits (Education)",
    "tier": 2,
    "status": "ENACTED (July 1, 2026)",
    "session": "2026 (ch. 2026-59)",
    "category": "education",
    "target": "Noncitizen, non-permanent-resident international students at state universities and Florida College System institutions; state financial aid recipients",
    "restrictions": "Educational restrictions",
    "penalties": "Ineligibility for preeminent funding; state financial aid restrictions",
    "summary": "Enacted as ch. 2026-59 (approved by the Governor May 1, 2026; effective July 1, 2026). Creates Fla. Stat. §1004.072 limiting nonresident degree-seeking students who are noncitizens and not permanent residents of the United States to no more than 10 percent at any state university or Florida College System institution and no more than 5 percent from any specific country. Requires preeminent state universities to reserve 95 percent of each new fall first-time-in-college enrolled cohort for Florida residents (based on a 3-year average) or become ineligible for preeminent funding by July 1, 2030. Requires students to be a US citizen or lawfully present to receive state financial aid. Passed the Senate 36-1 and House 81-16.",
    "civilRightsImpact": "Not China-specific on its face. The 5 percent per-country cap limits higher-education access by nationality for covered noncitizen, non-permanent-resident students, including Chinese student-visa holders. Graduate students are exempt from the per-country cap, and US citizens and lawful permanent residents are not restricted.",
    "keyProvisions": [
      "New Fla. Stat. §1004.072: noncitizen/non-LPR nonresident degree-seeking enrollment capped at 10% per institution and 5% per country (state universities and Florida College System)",
      "Preeminent state universities must reserve 95% of each fall FTIC cohort for Florida residents (3-year average) or lose preeminent funding by July 1, 2030",
      "State financial aid limited to US citizens and lawfully present individuals",
      "Graduate students exempt from the per-country enrollment cap; LPRs and US citizens unaffected",
      "Passed Senate 36-1, House 81-16"
    ],
    "url": "https://www.flsenate.gov/Session/Bill/2026/1279",
    "officialUrl": "https://www.flsenate.gov/Session/Bill/2026/1279/BillText/er/PDF",
    "introducedDate": "2026-01-13",
    "lastUpdated": "2026-05-05"
  },
  {
    "id": "id/property-H 356",
    "state": "ID",
    "stateName": "Idaho",
    "billNumber": "H 356",
    "title": "Property ownership restrictions on foreign principals (state assets, foreign adversaries)",
    "tier": 2,
    "status": "ENACTED (signed Apr 14, 2025; eff. Jul 1, 2025)",
    "session": "2025 (ch. 326)",
    "category": "property",
    "target": "Foreign principals from foreign adversaries — including any person domiciled in a foreign adversary (15 CFR 791.4 list: China, Russia, Iran, North Korea, Cuba, Venezuela) who is not a US citizen or lawful permanent resident; foreign adversary governments, officials, and political party members; organizations formed under foreign-adversary law; foreign governments and foreign state-controlled enterprises",
    "restrictions": "Property restrictions (acquisition bans; mandatory divestment; registration requirements)",
    "penalties": "Attorney general action, judicial foreclosure and forced sale; whistleblower reward of 30% of sale proceeds",
    "summary": "Amends Idaho Code §55-103 to bar foreign principal from acquiring, purchasing, or holding any controlling interest (except de minimis indirect interests under 5% of a publicly traded company) in agricultural land, water rights, mining claims, or mineral rights in Idaho, and bars foreign governments and foreign state-controlled enterprises from acquiring controlling interests in those plus forest land. Foreign principals must divest existing holdings within 180 days of the effective date, register agricultural land with the Idaho State Department of Agriculture and mining interests with the Department of Lands/Secretary of State within 60 days, and may acquire land only by devise/descent, security-interest enforcement, or debt collection with an 180-day resale obligation. Also enacts new §55-115 restricting lease or purchase of certain land or dwellings (military/critical-infrastructure adjacency). Exceptions for CFIUS national security agreements and foreign pension funds. Effective July 1, 2025 (signed Apr 14, 2025, Session Law Chapter 326).",
    "civilRightsImpact": "Directly restricts Chinese nationals who are not US citizens or lawful permanent residents and are domiciled in China (or another listed foreign adversary) from acquiring controlling interests in Idaho agricultural land, water rights, mining claims, and mineral rights, and requires divestment and registration of existing holdings — including holdings owned via visa status persons. US citizens and lawful permanent residents are exempt, so impact falls on non-immigrant visa holders and non-resident nationals (Tier 2). The whistleblower mechanism (30% of sale proceeds) creates private enforcement incentives against individuals, and the controlling-interest test (over 50%, or actual direction) reaches family-member holdings in entities.",
    "keyProvisions": [
      "Bars foreign principals from acquiring controlling interests in agricultural land, water rights, mining claims, mineral rights (de minimis <5% public equities exception)",
      "Bars foreign governments and state-controlled enterprises from controlling interests in those assets plus forest land",
      "180-day divestment requirement for pre-existing holdings; 60-day registration (ISDA / Dept of Lands / SOS)",
      "New §55-115: prohibitions on lease or purchase of certain land or dwellings; prohibition on access to state assets",
      "Whistleblower referrals for violations with rewards equal to 30% of sale proceeds (takes effect 180 days after enforcement date)",
      "AG enforcement via district court action and judicial foreclosure; CFIUS national security agreement and foreign pension fund exceptions",
      "Passed House 57-9-4 (3/14/25) and Senate 30-2-3 (4/3/25) as amended; House concurred 64-0-6; signed Apr 14, 2025; emergency clause, effective Jul 1, 2025"
    ],
    "url": "https://legislature.idaho.gov/sessioninfo/2025/legislation/H0356/",
    "officialUrl": "https://legislature.idaho.gov/wp-content/uploads/sessioninfo/2025/legislation/H0356E1.pdf",
    "introducedDate": "2025-03-03",
    "lastUpdated": "2025-07-01"
  },
  {
    "id": "in/education-SEA 256",
    "state": "IN",
    "stateName": "Indiana",
    "billNumber": "SEA 256",
    "title": "Foreign adversaries (foreign-student screening, foreign agent registration, real property)",
    "tier": 2,
    "status": "ENACTED (Public Law 131; signed Mar 5, 2026)",
    "session": "2026",
    "category": "education",
    "target": "Foreign students who are citizens of foreign adversaries (China, Russia, North Korea, Iran) and not US citizens, lawful permanent residents, or asylees, pursuing qualifying STEM programs (chemical, electrical, industrial, mechanical engineering; artificial intelligence; computer science; microbiology; virology)",
    "restrictions": "Educational restrictions",
    "penalties": "Denial of admission; unenrollment",
    "summary": "Enacted as Public Law 131 (signed March 5, 2026). Requires state educational institutions, beginning August 15, 2026, to complete a 'foreign influence and research security review' before admitting foreign students into qualifying STEM programs — reviewing affiliations, outside funding, and family ties (whether the student, spouse, parents, siblings, grandparents, aunts, or uncles are government employees, political party members, or members of united front organizations of a foreign adversary). Institutions may not admit students found to be agents of a foreign adversary or who refuse to provide information, must unenroll students who accept foreign-adversary funding, and must keep screening records for 10 years. Students enrolled by August 14, 2026 are grandfathered. Also creates a foreign agent registration chapter with the Attorney General (effective July 1, 2026, with reporting of >10% revenue transactions) and bars prohibited persons (agents of foreign adversaries) from acquiring Indiana real property.",
    "civilRightsImpact": "Applies to citizens of foreign adversaries (including China) who are not US citizens, LPRs, or asylees — including F-1 and J-1 students in STEM programs — and requires screening of students and relatives, including political-party membership questions. Refusal to cooperate can result in denial of admission, and covered foreign-adversary funding can require unenrollment. Unlike the failed House version (HB 1099), this measure was enacted. The real-property and registration provisions apply to persons found to be agents of a foreign adversary (conduct-based, not nationality-based).",
    "keyProvisions": [
      "Foreign influence and research security review before admitting foreign students to qualifying STEM programs (Aug 15, 2026)",
      "Review of affiliations, outside funding, and family ties to adversary governments, political parties, and united front organizations",
      "Bar on admitting agents of foreign adversaries or students who refuse to provide information",
      "Attestation against foreign-adversary funding; immediate unenrollment on violation",
      "10-year record retention; grandfathering for students enrolled by Aug 14, 2026",
      "Foreign agent registration with the Attorney General and >10% revenue transaction reporting (eff. July 1, 2026)",
      "Real-property ban for prohibited persons (agents of foreign adversaries)"
    ],
    "url": "https://iga.in.gov/legislative/2026/bills/senate/256/details",
    "officialUrl": "https://iga.in.gov/legislative/2026/bills/senate/256/details",
    "introducedDate": "2026-01-06",
    "lastUpdated": "2026-03-05"
  },
  {
    "id": "ks/property-SB 9",
    "state": "KS",
    "stateName": "Kansas",
    "billNumber": "SB 9",
    "title": "Kansas Land and Military Installation Protection Act",
    "tier": 2,
    "status": "ENACTED (2026; signed by Governor; eff. upon publication in statute book)",
    "session": "2025-2026",
    "category": "property",
    "target": "Foreign principals of countries of concern (China incl. Hong Kong SAR, Cuba, Iran, North Korea, Russia, Venezuela; foreign terrorist organizations under 8 U.S.C. §1189) — governments, officials, political parties, COC-domiciled entities, agents, and individuals who are citizens or residents of a COC and not US citizens or lawful permanent residents (nonimmigrant visa holders)",
    "restrictions": "Property restrictions",
    "penalties": "AG enforcement; civil forfeiture (KSA 60-4104/4106); registration and divestment obligations",
    "summary": "The Kansas Land and Military Installation Protection Act (2026) prohibits foreign principals from acquiring any interest in real property (other than residential) within 100 miles of any military installation — including installations in adjacent states (Fort Riley, Fort Leavenworth, McConnell AFB, etc.) — or in real property owned by the state or its subdivisions or connected to economic development programs. Covered foreign principals must register with the Attorney General within 90 days and divest existing holdings; violations are subject to AG enforcement and civil forfeiture. Foreign principals are also barred from all economic-development program benefits, and state and local governments may not purchase drone critical components produced by countries of concern or owned by foreign principals.",
    "civilRightsImpact": "The law includes nonimmigrant visa holders who are citizens or residents of China or another covered country within its 'foreign principal' definition while exempting LPRs and US citizens. Covered people face 90-day registration and divestment obligations, with forfeiture exposure, for property interests within 100 miles of military installations, including installations in adjacent states.",
    "keyProvisions": [
      "Bars foreign principals from acquiring interests in real property (excl. residential) within 100 miles of military installations, incl. installations in adjacent states",
      "Registration with the AG within 90 days; divestment of pre-existing holdings",
      "AG enforcement with civil forfeiture (KSA 60-4104/4106 amended)",
      "Foreign principals barred from economic-development program benefits",
      "State/local government drone critical-component procurement ban (COC-produced or foreign-principal-owned)"
    ],
    "url": "https://kslegislature.gov/b2025_26/bills/sb9/",
    "officialUrl": "https://kslegislature.gov/documents/view-leg/?apn=b2025_26/year2/ready_for_publication/sb_9/sb9_enrolled.pdf",
    "introducedDate": "2025-01-13",
    "lastUpdated": "2026-08-17"
  },
  {
    "id": "ar/education-HB 1561",
    "state": "AR",
    "stateName": "Arkansas",
    "billNumber": "HB 1561",
    "title": "Higher education applicant screening and travel monitoring (research security)",
    "tier": 2,
    "status": "ENACTED (Act 473, 2025)",
    "session": "2025 (Act 473)",
    "category": "research",
    "target": "Research applicants at Arkansas institutions with $10M+ annual federal research expenditures who are citizens of a foreign adversary (China, Russia, Iran, North Korea, Cuba, Venezuela) and not lawful permanent residents",
    "restrictions": "Educational restrictions",
    "penalties": "Class D felony for trade-secret theft benefiting a foreign government",
    "summary": "Act 473 (2025) requires institutions of higher education with $10 million or more in annual federal research expenditures to screen applicants for research positions, graduate and undergraduate research positions, and visiting researcher appointments who are citizens of a foreign adversary and not lawful permanent residents. Screening requires disclosure of CVs, employment history since age 18, publications, funding sources, organizational affiliations (including military service), and patents, verified against federal sanction lists. Institutions must also adopt a travel approval and monitoring program for all faculty and researchers traveling to foreign adversary countries (by Jan 1, 2026). Misappropriation of trade secrets benefiting a foreign government becomes a Class D felony. Passed House 81-10, Senate 29-5.",
    "civilRightsImpact": "Restricts Chinese nationality-based access to paid research roles (postdocs, RA/TA positions, visiting research appointments) at major Arkansas research universities: non-LPR citizens of foreign adversaries — including F-1/J-1 visa holders — face nationality-triggered disclosure, screening, and verification requirements tied to federal lists that include China. Faculty-level travel to China also becomes subject to institutional approval and monitoring. LPRs and US citizens are exempt from screening.",
    "keyProvisions": [
      "Screening of foreign-adversary-citizen, non-LPR applicants for research/grad/undergrad research and visiting researcher positions",
      "Disclosure of CV, employment history since 18, publications, funding, affiliations, military service, patents",
      "Verification against federal sanction lists (Commerce Entity List, Military End-User List, etc.)",
      "Travel approval and monitoring program for faculty/researchers to foreign adversary countries (by Jan 1, 2026)",
      "Trade-secret misappropriation benefiting a foreign government: Class D felony",
      "Passed House 81-10, Senate 29-5"
    ],
    "url": "https://www.arkleg.state.ar.us/Bills/Detail?id=HB1561&ddBienniumSession=2025%2F2025R",
    "officialUrl": "https://www.arkleg.state.ar.us/Home/FTPDocument?path=/ACTS/2025R/Public/ACT473.pdf",
    "introducedDate": "2025-03-12",
    "lastUpdated": "2025-04-08"
  },
  {
    "id": "tx/education-HB 127",
    "state": "TX",
    "stateName": "Texas",
    "billNumber": "HB 127",
    "title": "Texas Higher Education Research Security Act (screening, partnerships, travel)",
    "tier": 2,
    "status": "ENACTED (89th Legislature; signed June 20, 2025; eff. Sept 1, 2025)",
    "session": "89th Legislature (2025)",
    "category": "research",
    "target": "Researchers who are citizens of foreign adversaries and not lawful permanent residents at Texas institutions of higher education; academic partnerships and gifts from foreign sources of foreign adversaries",
    "restrictions": "Educational restrictions",
    "penalties": "Not specified",
    "summary": "Creates the Texas Higher Education Research Security Council (Education Code §51B.101) and enacts Chapter 51B: institutions may not enter academic partnerships with foreign sources of foreign adversaries that constrain freedom of contract, curriculum control, or research integrity (§51B.102); restricts certain student associations and foreign-source gifts (§51B.103); requires institutions to screen foreign-citizen, non-LPR researchers — including review of passport and visa application materials — before research employment or access to research data (§51B.151); requires a travel approval program for faculty and researcher travel to foreign adversary countries; and requires review of education software linked to foreign adversaries.",
    "civilRightsImpact": "Subjects Chinese nationals who are not lawful permanent residents to nationality-triggered screening — including passport and visa application review — before taking research employment or accessing research data at Texas institutions, and places faculty/researcher travel to China under institutional approval and monitoring. LPRs and US citizens are exempt. China is among the foreign adversaries covered.",
    "keyProvisions": [
      "Creates the Higher Education Research Security Council (§51B.101)",
      "Bans academic partnerships with foreign sources of foreign adversaries constraining freedom of contract/curriculum control (§51B.102)",
      "Restricts certain student associations and foreign-source gifts (§51B.103)",
      "Screening of foreign-citizen, non-LPR researchers incl. passport and visa application materials before research employment or data access (§51B.151)",
      "Travel approval program; education software review",
      "Signed June 20, 2025; effective Sept 1, 2025"
    ],
    "url": "https://capitol.texas.gov/tlodocs/89R/billtext/html/HB00127F.htm",
    "officialUrl": "https://capitol.texas.gov/tlodocs/89R/billtext/html/HB00127F.htm",
    "introducedDate": "2025-01-14",
    "lastUpdated": "2025-09-01"
  },
  {
    "id": "tn/property-HB 1788",
    "state": "TN",
    "stateName": "Tennessee",
    "billNumber": "HB 1788",
    "title": "Prohibited foreign party restrictions on non-agricultural real property",
    "tier": 2,
    "status": "ENACTED (Public Chapter 733; effective July 1, 2026)",
    "session": "114th General Assembly",
    "category": "property",
    "target": "Prohibited foreign parties — individuals who are citizens or residents of ITAR-listed countries (22 C.F.R. §126.1; includes China) and not US citizens or 'qualified aliens' (8 U.S.C. §1641(b)) — and prohibited foreign-party-controlled businesses",
    "restrictions": "Property restrictions",
    "penalties": "Class A misdemeanor ($1,500 fine / up to 11 months 29 days imprisonment); $2,000 civil penalty; 2-year divestment",
    "summary": "Public Chapter 733 (HB 1788) extends Tennessee's non-agricultural real property restriction from prohibited foreign-party-controlled businesses to prohibited foreign parties themselves — now including individuals — and replaces the prior 'resident alien' exemption with the narrower 'qualified alien' definition under 8 U.S.C. §1641(b). Prohibited foreign parties must register with the Secretary of State and divest non-agricultural real property interests within two years. Violations are a Class A misdemeanor and carry a $2,000 civil penalty. Effective July 1, 2026.",
    "civilRightsImpact": "Individual Chinese nationals (citizens or residents of ITAR-listed countries) who are not US citizens or 'qualified aliens' — including most nonimmigrant visa holders — become barred from acquiring non-agricultural real property in Tennessee, with registration, divestment, criminal misdemeanor, and civil penalty exposure. The narrowed exemption (previously any US resident alien; now only 8 U.S.C. §1641(b) qualified aliens such as LPRs) tightens coverage versus prior law. LPRs and US citizens remain exempt.",
    "keyProvisions": [
      "Extends the non-agricultural land restriction to prohibited foreign parties as individuals (amends Tenn. Code Title 66, Ch. 2, Part 3)",
      "PFP definition: citizens/residents of ITAR-listed countries (22 C.F.R. §126.1) not US citizens or qualified aliens (8 U.S.C. §1641(b))",
      "Replaces the prior resident-alien exemption with the narrower qualified-alien exemption",
      "Secretary of State registration; 2-year divestment",
      "Class A misdemeanor and $2,000 civil penalty for violations",
      "Effective July 1, 2026"
    ],
    "url": "https://wapp.capitol.tn.gov/apps/BillInfo/Default?BillNumber=HB1788&ga=114",
    "officialUrl": "https://www.capitol.tn.gov/Bills/114/Bill/HB1788.pdf",
    "introducedDate": "2025-02-03",
    "lastUpdated": "2026-07-01"
  },
  {
    "id": "tn/property-HB 2547",
    "state": "TN",
    "stateName": "Tennessee",
    "billNumber": "HB 2547",
    "title": "Expansion of prohibited foreign party restrictions to mineral and water rights",
    "tier": 2,
    "status": "ENACTED (Public Chapter 806; effective April 21, 2026)",
    "session": "114th General Assembly",
    "category": "property",
    "target": "Prohibited foreign parties (individuals) and prohibited foreign-party-controlled businesses; covered interests now include mineral rights (oil, gas, coal, lignite, brine, groundwater, surface water) and designations under 15 C.F.R. Part 791 Subpart A",
    "restrictions": "Property restrictions",
    "penalties": "60-day registration; divestment; civil penalties",
    "summary": "Public Chapter 806 (HB 2547) expands Tennessee Code §66-2-302 to cover mineral and water interests (oil, gas, coal, lignite, brine, groundwater, surface water) and updates the covered-country list to include designations under 15 C.F.R. Part 791 Subpart A. Tightens the 'significant interest' thresholds for prohibited foreign-party control from 33% to 10% for individuals and from 50% to 33% for groups acting in concert; requires registration within 60 days; adds an exception for CFIUS 'controlled coverage' transactions (31 C.F.R. §800.210). Effective April 21, 2026.",
    "civilRightsImpact": "Deepens the individual-level restriction established by Public Chapter 733 by extending the prohibited-party ban to mineral and water interests — significant in Tennessee's natural gas and aquifer regions — and by lowering the interest thresholds that trigger the business-control presumption (10% held by individual prohibited foreign parties). Nonimmigrant visa holders who are citizens or residents of listed countries, including China, remain covered individuals.",
    "keyProvisions": [
      "Extends prohibited-party restrictions to mineral rights (oil, gas, coal, lignite, brine, groundwater, surface water)",
      "Adds 15 C.F.R. Part 791 Subpart A designations to the covered-country list",
      "Significant-interest thresholds lowered: 33% to 10% (individuals), 50% to 33% (groups acting in concert)",
      "60-day registration requirement",
      "CFIUS controlled-coverage exception (31 C.F.R. §800.210)",
      "Effective April 21, 2026"
    ],
    "url": "https://wapp.capitol.tn.gov/apps/BillInfo/Default?BillNumber=HB2547&ga=114",
    "officialUrl": "https://www.capitol.tn.gov/Bills/114/Bill/HB2547.pdf",
    "introducedDate": "2025-01-23",
    "lastUpdated": "2026-04-21"
  },
  {
    "id": "la/property-SB 200",
    "state": "LA",
    "stateName": "Louisiana",
    "billNumber": "SB 200",
    "title": "Immovable property prohibition for foreign adversaries and prohibited foreign actors (military-adjacent land, expropriation)",
    "tier": 2,
    "status": "ENACTED (2026 Regular Session; effective Aug 1, 2026)",
    "session": "2026 Regular Session",
    "category": "property",
    "target": "Foreign adversaries (15 C.F.R. 791.4 countries incl. China and Hong Kong SAR, Cuba, Iran, North Korea, Russia, Venezuela under Maduro) and 'prohibited foreign actors' — citizens of a foreign adversary who are not lawful permanent residents or DHS-authorized lawfully present individuals",
    "restrictions": "Property restrictions",
    "penalties": "Contract rescission; AG injunctive relief; $50,000 civil penalty and forfeiture (extension beyond farmland); military expropriation within 50 miles of national security infrastructure",
    "summary": "SB 200 (2026 Regular Session) amends R.S. 9:2717.1: redefines the covered individual as a 'prohibited foreign actor' (any citizen of a foreign adversary unless a lawful permanent resident or lawfully present pursuant to DHS authorization), extends the immovable-property prohibition to individuals for both farmland and all other immovable property (prior law limited the general immovable ban to business entities), extends AG injunctive relief, investigative demands, and forfeiture/receivership remedies to all immovable property, and authorizes the state Military Department to expropriate immovable property purchased, leased, possessed, or controlled by a foreign adversary or prohibited foreign actor within 50 miles of national security infrastructure regardless of acquisition date. Extends the $50,000 farmland civil penalty to all immovable property and retains the CFIUS national-security-agreement exception.",
    "civilRightsImpact": "Individual Chinese nationals (and citizens of other listed foreign adversaries) who are not LPRs and not DHS-authorized lawfully present — including other nonimmigrant visa holders and undocumented nationals — face expanded property prohibitions in Louisiana: prior law's entity-only immovable ban becomes an individual ban covering all immovable property, with AG enforcement, $50,000 penalties, forfeiture, and expropriation exposure near national security infrastructure. LPRs and lawfully present individuals are exempt.",
    "keyProvisions": [
      "Redefines 'prohibited foreign actor' as citizens of foreign adversaries unless LPR or DHS-lawfully-present",
      "Extends the immovable-property ban from business entities to individuals for all immovable property (farmland and other)",
      "AG injunctive relief, investigative demands, forfeiture, and receivership extended to all immovable property",
      "Military Department expropriation of covered property within 50 miles of national security infrastructure (regardless of acquisition date)",
      "$50,000 civil penalty extended from farmland to all immovable property",
      "CFIUS national security agreement exception; effective Aug 1, 2026"
    ],
    "url": "https://www.legis.la.gov/legis/BillInfo.aspx?s=26RS&b=SB200",
    "officialUrl": "https://www.legis.la.gov/legis/ViewDocument.aspx?d=1480166",
    "introducedDate": "2026-04-13",
    "lastUpdated": "2026-08-01"
  },
  {
    "id": "tn/property-HB 40",
    "state": "TN",
    "stateName": "Tennessee",
    "billNumber": "HB 40",
    "title": "Sanctioned nonresident alien real-property restrictions",
    "tier": 2,
    "status": "ENACTED (Public Chapter 369; effective July 1, 2023)",
    "session": "113th General Assembly",
    "category": "property",
    "target": "Sanctioned nonresident aliens — citizens of OFAC-sanctioned foreign governments or persons identified through OFAC sanctions programs — excluding US citizens and lawful permanent residents; sanctioned foreign businesses and governments",
    "restrictions": "Property restrictions",
    "penalties": "Registration; two-year divestment; escheat and court-ordered sale; civil penalty up to $2,000 per registration violation",
    "summary": "Public Chapter 369 bars a 'sanctioned nonresident alien,' sanctioned foreign business, or sanctioned foreign government from purchasing or otherwise acquiring Tennessee real property. The enacted definition reaches an individual who is a citizen of a government identified through OFAC sanctions programs or who is individually identified through those programs, but expressly excludes US citizens and lawful permanent residents. Covered owners must register with the Secretary of State, and prohibited acquisitions can be escheated and sold by court order.",
    "civilRightsImpact": "Reaches nonimmigrant visa holders and other non-LPR nationals when an OFAC sanctions hook applies, including covered Chinese nationals, while exempting US citizens and lawful permanent residents. It does not prohibit all Chinese nationals categorically; coverage depends on the foreign-government or individual OFAC designation. Covered people face registration, divestment, escheat, and civil-penalty exposure.",
    "keyProvisions": [
      "Defines a sanctioned nonresident alien through OFAC government or individual sanctions designations",
      "Explicitly exempts US citizens and lawful permanent residents",
      "Prohibits covered people from purchasing or otherwise acquiring Tennessee real property",
      "Requires registration with the Secretary of State and two-year divestment in specified cases",
      "Authorizes escheat and court-ordered sale; up to $2,000 per registration violation",
      "Signed May 11, 2023; effective July 1, 2023"
    ],
    "url": "https://wapp.capitol.tn.gov/apps/BillInfo/Default?BillNumber=HB0040&ga=113",
    "officialUrl": "https://www.capitol.tn.gov/Bills/113/Bill/HB0040.pdf",
    "introducedDate": "2023-01-10",
    "lastUpdated": "2023-07-01"
  },
  {
    "id": "ne/property-LB 1301",
    "state": "NE",
    "stateName": "Nebraska",
    "billNumber": "LB 1301",
    "title": "Foreign-owned Real Estate National Security Act",
    "tier": 2,
    "status": "ENACTED (approved April 16, 2024; operative Jan 1, 2025)",
    "session": "108th Legislature (2024)",
    "category": "property",
    "target": "Nonresident aliens who are not US citizens, US nationals, or lawful permanent residents and have been physically present in the US for fewer than 183 days during the current and preceding two years; OFAC-listed and Commerce-designated restricted persons and entities",
    "restrictions": "Property restrictions",
    "penalties": "Attorney General investigation and subpoenas; mandatory divestment; public auction; up to $50,000 per parcel for prohibited transfers",
    "summary": "LB 1301 adopted the Foreign-owned Real Estate National Security Act and modernized Nebraska's alien land restrictions. It generally bars a defined nonresident alien from acquiring Nebraska real estate or a leasehold longer than five years, subject to statutory urban, industrial, inheritance, and security-interest exceptions. It also removes key exceptions for a 'restricted entity,' including any person on OFAC sanctions lists or determined under 15 C.F.R. §7.4 to present a serious national-security concern, and creates Attorney General investigation, divestment, and sale procedures.",
    "civilRightsImpact": "The nonresident-alien definition expressly exempts US citizens, US nationals, lawful permanent residents, and people meeting the law's 183-day physical-presence test, but can reach recently arrived F-1, J-1, H-1B, and other visa holders, including Chinese nationals. Covered property can be forcibly divested and sold. Separately, federally restricted individuals face broader restrictions without the ordinary urban and industrial exceptions.",
    "keyProvisions": [
      "Nonresident alien excludes US citizens, US nationals, LPRs, and people meeting a 183-day physical-presence test",
      "Generally bars covered people from real estate and leaseholds longer than five years, with limited exceptions",
      "Restricted persons include OFAC-listed persons and Commerce-designated national-security threats",
      "Removes urban and industrial exceptions for restricted persons and entities",
      "AG subpoenas, mandatory divestment, receiver sale, and up to $50,000 per prohibited transfer",
      "Approved April 16, 2024; operative January 1, 2025"
    ],
    "url": "https://nebraskalegislature.gov/bills/view_bill.php?DocumentID=55575&docnum=LB1301&leg=108",
    "officialUrl": "https://nebraskalegislature.gov/FloorDocs/108/PDF/Final/LB1301.pdf",
    "introducedDate": "2024-01-16",
    "lastUpdated": "2025-01-01"
  },
  // ENACTED BILLS - Tier 1: affect LPRs/US citizens
  {
    "id": "al/government-HB 379",
    "state": "AL",
    "stateName": "Alabama",
    "billNumber": "HB 379",
    "title": "Alabama Property Protection Act",
    "tier": 1,
    "status": "ENACTED (effective Aug 1, 2023)",
    "session": "2023",
    "category": "property",
    "target": "Foreign principals: governments, officials, and political party members of China, Iran, North Korea, Russia; OFAC-sanctioned governments (Taiwan excluded)",
    "restrictions": "Property restrictions",
    "penalties": "Not specified",
    "summary": "Prohibits 'foreign principals' — the government of a foreign country of concern (China, Iran, North Korea, Russia), its officials, members of its ruling political parties, and OFAC-sanctioned governments — from acquiring title to or a controlling interest in agricultural or forest land, or real property within 10 miles of military installations or critical infrastructure (Ala. Code §35-1-1.1). Taiwan is explicitly excluded. Ordinary Chinese nationals and residents are not restricted by the law.",
    "civilRightsImpact": "The operative definition reaches Chinese nationals as individuals only if they are government officials or members of a covered political party, such as the Chinese Communist Party. It does not categorically restrict ordinary Chinese citizens, lawful permanent residents, or other residents based on nationality alone.",
    "keyProvisions": [
      "Prohibits 'foreign principals' from acquiring agricultural/forest land or property within 10 miles of military installations or critical infrastructure",
      "'Foreign principal' = government or officials of China, Iran, North Korea, or Russia; political party members; OFAC-sanctioned governments",
      "Explicitly excludes Taiwan",
      "Applies to acquisitions on or after Aug 1, 2023"
    ],
    "url": "https://alison.legislature.state.al.us/bill-search?bill=HB379",
    "officialUrl": "https://alison.legislature.state.al.us/files/pdf/SearchableInstruments/2023RS/HB379-enr.pdf",
    "introducedDate": "2023-01-09",
    "lastUpdated": "2023-08-01"
  },
  {
    "id": "fl/other-HB 905",
    "state": "FL",
    "stateName": "Florida",
    "billNumber": "HB 905",
    "title": "Foreign Interference Restriction and Enforcement Act (adoption and surrogacy prohibitions, foreign influence)",
    "tier": 1,
    "status": "ENACTED (ch. 2026-66; approved by Governor May 8, 2026; eff. July 1, 2026)",
    "session": "2026 (ch. 2026-66)",
    "category": "other",
    "target": "Citizens or residents of foreign countries of concern (Fla. Stat. §286.101(1); includes China) — no US-citizenship or LPR exemption for the adoption/surrogacy prohibitions; public officials and employees (gift and ethics provisions)",
    "restrictions": "Family-formation restrictions; ethics and foreign-influence restrictions",
    "penalties": "Void and unenforceable contracts; ethics penalties; criminal penalty reclassification; business tax receipt revocation",
    "summary": "The Foreign Interference Restriction and Enforcement Act (ch. 2026-66) prohibits a preplanned adoption agreement if the volunteer mother, intended father, or intended mother is a citizen or resident of a foreign country of concern (Fla. Stat. §63.213), prohibits a gestational surrogacy contract if any party to the contract is a citizen or resident of a foreign country of concern (§742.15), and declares such contracts void and unenforceable. Also expands 'foreign source of concern' to include designated foreign terrorist organizations; increases ethics penalties for gifts received from covered sources; reclassifies criminal offenses committed to benefit a foreign government, designated foreign terrorist organization, or their agents; authorizes tax collectors to revoke or refuse to renew business tax receipts for unlawful Cuba business; repeals the Florida-China Institute from the linkage-institute list; and prohibits camera-system contracts with vendors of foreign countries of concern.",
    "civilRightsImpact": "The adoption and surrogacy prohibitions apply to citizens or residents of a foreign country of concern with no exemption for US citizens or lawful permanent residents. A person who is a U.S. citizen or LPR but also falls within the statute's covered foreign-country classification can therefore be barred from a preplanned adoption agreement or gestational surrogacy contract (Tier 1).",
    "keyProvisions": [
      "Prohibits preplanned adoption agreements when the volunteer mother, intended father, or intended mother is a citizen or resident of a foreign country of concern (Fla. Stat. §63.213)",
      "Prohibits gestational surrogacy contracts when any party is a citizen or resident of a foreign country of concern (§742.15); contracts void and unenforceable",
      "Expands 'foreign source of concern' to include designated foreign terrorist organizations",
      "Increases ethics penalties for gifts from covered sources; criminal penalty reclassification for offenses benefiting covered foreign governments/organizations",
      "Business tax receipt revocation/refusal for unlawful Cuba operations",
      "Repeals the Florida-China Institute from the linkage-institute list (§288.8175)",
      "Camera-system contract ban with vendors of foreign countries of concern (§316.0078); effective July 1, 2026"
    ],
    "url": "https://www.flsenate.gov/Session/Bill/2026/905",
    "officialUrl": "https://www.flsenate.gov/Session/Bill/2026/905/BillText/er/PDF",
    "introducedDate": "2026-01-13",
    "lastUpdated": "2026-05-11"
  },
  {
    "id": "nh/property-2025 Ch. 141",
    "state": "NH",
    "stateName": "New Hampshire",
    "billNumber": "2025 Ch. 141",
    "title": "Statewide real-property ban for foreign principals from countries of concern",
    "tier": 1,
    "status": "ENACTED (RSA 477:22-b–f; effective June 27, 2025)",
    "session": "2025 Session Law, Chapter 141",
    "category": "property",
    "target": "Governments, officials, companies, and natural-person employees or agents of China, Russia, Iran, Syria, and North Korea; no US-citizen or lawful-permanent-resident exemption for covered employees or agents",
    "restrictions": "Property restrictions",
    "penalties": "Class B felony for a natural person; seizure and civil forfeiture of real property",
    "summary": "New Hampshire RSA 477:22-b through 477:22-f prohibits a 'foreign principal' from acquiring any permanent or temporary ownership or controlling interest in real property anywhere in New Hampshire and from leasing or otherwise occupying or controlling such property. A foreign principal includes any natural person who is an employee or agent of China, Russia, Iran, Syria, or North Korea, as well as listed governments, officials, and country-based entities.",
    "civilRightsImpact": "The natural-person clause contains no exemption for US citizens or lawful permanent residents. A Chinese American citizen or LPR who is deemed an employee or agent of the PRC could be barred from owning or leasing property statewide, prosecuted for a Class B felony, and subjected to property seizure and forfeiture. Ordinary Chinese nationals without the specified employment or agency relationship are not covered.",
    "keyProvisions": [
      "Statewide ban on permanent or temporary ownership, control, lease, or occupancy of real property",
      "Foreign principal includes natural-person employees or agents of China and four other countries of concern",
      "No US-citizen or LPR exemption for covered employees or agents",
      "Class B felony for a natural-person violation",
      "State seizure, lien, forfeiture proceeding, and public-auction authority",
      "Effective June 27, 2025"
    ],
    "url": "https://gc.nh.gov/rsa/html/XLVIII/477/477-22-b.htm",
    "officialUrl": "https://gc.nh.gov/rsa/html/XLVIII/477/477-22-c.htm",
    "introducedDate": "",
    "lastUpdated": "2025-06-27"
  },
  {
    "id": "la/education-SB 399",
    "state": "LA",
    "stateName": "Louisiana",
    "billNumber": "SB 399",
    "title": "Research and Education Protection Act (foreign-adversary affiliation screening)",
    "tier": 1,
    "status": "ENACTED (Act 505; effective Jan 1, 2027)",
    "session": "2026 Regular Session",
    "category": "education",
    "target": "Applicants for enrollment, employment, or research funding at Louisiana public postsecondary institutions who have current or former participation in a federally identified malign foreign talent recruitment program or affiliation with specified PRC/CCP/PLA/intelligence-linked entities",
    "restrictions": "Educational and employment screening",
    "penalties": "Denial, conditioning, or termination of enrollment, employment, or research opportunities; perjury and institutional penalties",
    "summary": "Act 505 creates the Louisiana Higher Education Research Security Council and a broad foreign-adversary compliance system. Public postsecondary applicants for enrollment, employment, or research funding must disclose current or former participation in a federally identified malign foreign talent recruitment program and affiliations with specified foreign-adversary entities, including PRC government, CCP, PLA, intelligence, United Front, Entity List, and Military End-User-linked organizations. Institutions must perform an individualized risk assessment before denying, conditioning, or terminating an opportunity.",
    "civilRightsImpact": "The disclosure and adverse-action provisions can reach US citizens and lawful permanent residents because they turn on current or former organizational affiliation, not immigration status. The law says screening must be uniform and not based solely on citizenship, nationality, or country of origin, and that mere past, incidental, or nominal CCP membership is insufficient by itself; nevertheless, Chinese-origin applicants with covered affiliations face mandatory disclosure, risk review, and possible denial or termination of education, employment, or research access.",
    "keyProvisions": [
      "Mandatory affiliation disclosures for enrollment, employment, and research-funding applicants",
      "Express coverage of specified PRC, CCP, PLA, intelligence, United Front, Entity List, and Military End-User-linked entities",
      "Individualized, fact-specific risk assessment before adverse action",
      "Adverse action limited to articulated espionage, influence, unlawful technology-transfer, research-integrity, or legal risks",
      "Mere past, incidental, or nominal political-party membership is not sufficient by itself",
      "Signed as Act 505; effective January 1, 2027"
    ],
    "url": "https://legis.la.gov/legis/BillInfo.aspx?s=26RS&b=SB399",
    "officialUrl": "https://legis.la.gov/legis/ViewDocument.aspx?d=1480205",
    "introducedDate": "2026-03-09",
    "lastUpdated": "2026-05-25"
  },
  {
    "id": "ok/property-HB 3431",
    "state": "OK",
    "stateName": "Oklahoma",
    "billNumber": "HB 3431",
    "title": "Expansion of alien and foreign-adversary land and critical-mineral restrictions",
    "tier": 1,
    "status": "ENACTED (approved May 11, 2026; effective Nov 1, 2026)",
    "session": "60th Legislature (2025-2026)",
    "category": "property",
    "target": "Any alien or person who is not a US citizen; foreign terrorist organizations, specially designated nationals, foreign government adversaries, and covered enterprises",
    "restrictions": "Property and critical-mineral restrictions",
    "penalties": "Deed affidavit and recording refusal; enforcement under Oklahoma alien-land law",
    "summary": "HB 3431 amends 60 O.S. §121 to prohibit any alien or person who is not a US citizen, as well as foreign terrorist organizations, OFAC specially designated nationals, and foreign government adversaries, from acquiring, owning, or leasing Oklahoma land or critical minerals directly or through an entity, trust, or foreign government enterprise. It retains a regulated-interstate-commerce and CFIUS national-security-agreement exception and requires a notarized compliance affidavit with deeds recorded after November 1, 2023.",
    "civilRightsImpact": "The operative individual clause covers every person who is not a US citizen and contains no lawful-permanent-resident exemption. It therefore directly reaches Chinese green-card holders as well as Chinese visa holders, alongside noncitizens of every nationality. The amendment also adds China-relevant foreign-adversary and OFAC hooks and extends the restriction from land to critical minerals.",
    "keyProvisions": [
      "Bars any non-US citizen from acquiring, owning, or leasing land or critical minerals",
      "No lawful-permanent-resident exemption in the operative clause",
      "Adds foreign terrorist organizations, OFAC specially designated nationals, and hostile/CPC foreign governments",
      "Applies through business entities, trusts, and foreign government enterprises",
      "Requires a notarized compliance affidavit for covered deed recordings",
      "Approved May 11, 2026; effective November 1, 2026"
    ],
    "url": "https://www.oklegislature.gov/BillInfo.aspx?Bill=HB3431&Session=2600",
    "officialUrl": "https://www.oklegislature.gov/cf_pdf/2025-26%20ENR/hB/HB3431%20ENR.PDF",
    "introducedDate": "2026-02-02",
    "lastUpdated": "2026-05-11"
  },
  // PENDING BILLS
  {
    "id": "ny/property-A 6154",
    "state": "NY",
    "stateName": "New York",
    "billNumber": "A 6154",
    "title": "Prohibiting certain noncitizens and foreign entities from taking industrial and agricultural real property",
    "tier": 1,
    "status": "In Committee (Judiciary)",
    "session": "2025-2026",
    "category": "property",
    "target": "Citizens of foreign countries of particular concern (US State Dept list — includes China) — no exemption for lawful permanent residents; foreign governments, companies, and entities of particular concern",
    "restrictions": "Property restrictions",
    "penalties": "Not specified",
    "summary": "Would amend N.Y. Real Property Law §10 to prohibit noncitizens, foreign governments, and foreign entities from taking any real property zoned industrial, light industrial, heavy industrial, residential agricultural, agricultural, or rural agricultural. Applies to (a) governmental entities of countries of particular concern, (b) companies headquartered in, held or controlled by, or majority-owned by citizens of such countries, and (c) individual citizens of countries of particular concern, as identified by the US Department of State. Introduced by Assemblymember Lemondes; referred to the Judiciary Committee Feb 26, 2025 and re-referred Jan 7, 2026; held for consideration.",
    "civilRightsImpact": "The operative clause bars 'an individual who is a citizen of any foreign country of particular concern' with no exemption for lawful permanent residents. Because China is on the incorporated State Department list, a Chinese citizen who is an LPR would be prohibited from taking covered industrial- and agricultural-zoned property in New York. Residential property outside the listed zoning categories is not covered. Pending; no committee vote.",
    "keyProvisions": [
      "Prohibits noncitizens, foreign governments, and foreign entities of countries of particular concern from taking industrial/agricultural/agricultural-residential-zoned real property",
      "Operative clause (c) covers individual citizens of such countries — no LPR exemption",
      "Severability clause; immediate effective date",
      "Referred to Judiciary Committee 2/26/2025 and 1/7/2026; held for consideration"
    ],
    "url": "https://assembly.ny.gov/leg/?bn=A06154",
    "officialUrl": "https://legislation.nysenate.gov/pdf/bills/2025/A6154",
    "introducedDate": "2025-02-26",
    "lastUpdated": "2026-01-07"
  },
  {
    "id": "ny/property-A 1452",
    "state": "NY",
    "stateName": "New York",
    "billNumber": "A 1452",
    "title": "Prohibiting governmental entities, companies, and individuals of foreign countries of particular concern from taking real property",
    "tier": 1,
    "status": "In Committee (Judiciary; re-referred Jan 7, 2026)",
    "session": "2025-2026",
    "category": "property",
    "target": "Governmental entities of particular concern and companies majority-owned/controlled by them (US State Dept list — includes China), and any individual who is a citizen of a foreign country of particular concern — no exemption for lawful permanent residents — taking real property in New York",
    "restrictions": "Property restrictions",
    "penalties": "Not specified",
    "summary": "Would amend N.Y. Real Property Law §10 to bar (a) governmental entities of foreign countries of particular concern, (b) companies majority-owned or controlled by such entities, and (c) any individual who is a citizen of a foreign country of particular concern from taking real property in New York, and would require disposition of existing covered holdings. The individual provision contains no LPR or US-citizen exemption and covers all real property, including residential property. Introduced and referred to the Assembly Judiciary Committee Jan 9, 2025; re-referred Jan 7, 2026. Pending; no committee vote.",
    "civilRightsImpact": "The operative individual clause bars 'an individual who is a citizen of any foreign country of particular concern' from taking any real property in New York and contains no exemption for lawful permanent residents. Because China is on the incorporated State Department list, covered Chinese citizens, including LPRs, would be required to dispose of existing holdings and could not take new residential or other real property (Tier 1).",
    "keyProvisions": [
      "Bars individual citizens of countries of particular concern from taking real property in New York — no LPR or US-citizen exemption",
      "Also bars governmental entities of particular concern and majority-owned/controlled companies",
      "Covers all real property, including residential (amends Real Property Law §10)",
      "Existing covered holdings would need to be disposed of",
      "Effective immediately upon enactment; severability clause",
      "Referred to Assembly Judiciary 1/9/2025; re-referred 1/7/2026"
    ],
    "url": "https://assembly.ny.gov/leg/?bn=A01452",
    "officialUrl": "https://legislation.nysenate.gov/pdf/bills/2025/A1452",
    "introducedDate": "2025-01-09",
    "lastUpdated": "2026-01-07"
  },
  {
    "id": "ny/property-S 5651",
    "state": "NY",
    "stateName": "New York",
    "billNumber": "S 5651",
    "title": "Prohibiting governmental entities, companies, and individuals of foreign countries of particular concern from taking real property",
    "tier": 1,
    "status": "In Committee (Judiciary; re-referred Jan 7, 2026)",
    "session": "2025-2026",
    "category": "property",
    "target": "Governmental entities of particular concern and companies majority-owned/controlled by them (US State Dept list — includes China), and any individual who is a citizen of a foreign country of particular concern — no exemption for lawful permanent residents — taking real property in New York",
    "restrictions": "Property restrictions",
    "penalties": "Not specified",
    "summary": "Senate companion to A 1452. Would amend N.Y. Real Property Law §10 to bar governmental entities, covered companies, and individual citizens of foreign countries of particular concern from taking real property in New York, and would require disposition of existing covered holdings. The individual provision contains no LPR or US-citizen exemption and covers all real property, including residential property. Referred to the Senate Judiciary Committee Feb 26, 2025 and re-referred Jan 7, 2026. Pending; no committee vote.",
    "civilRightsImpact": "The operative individual clause bars 'an individual who is a citizen of any foreign country of particular concern' from taking any real property in New York and contains no exemption for lawful permanent residents. Because China is on the incorporated State Department list, covered Chinese citizens, including LPRs, would be required to dispose of existing holdings and could not take new residential or other real property (Tier 1).",
    "keyProvisions": [
      "Bars individual citizens of countries of particular concern from taking real property in New York — no LPR or US-citizen exemption",
      "Also bars governmental entities of particular concern and majority-owned/controlled companies",
      "Covers all real property, including residential (amends Real Property Law §10)",
      "Existing covered holdings would need to be disposed of",
      "Effective immediately upon enactment; severability clause",
      "Referred to Senate Judiciary 2/26/2025; re-referred 1/7/2026"
    ],
    "url": "https://assembly.ny.gov/leg/?bn=S05651",
    "officialUrl": "https://legislation.nysenate.gov/pdf/bills/2025/S5651",
    "introducedDate": "2025-02-26",
    "lastUpdated": "2026-01-07"
  },
  {
    "id": "ok/contract-SB 2073",
    "state": "OK",
    "stateName": "Oklahoma",
    "billNumber": "SB 2073",
    "title": "Hire Oklahomans Act (H-1B/OPT employment ban at state entities)",
    "tier": 2,
    "status": "In Committee (Rules)",
    "session": "2026",
    "category": "contract",
    "target": "H-1B visa holders and Optional Practical Training (OPT) participants of all nationalities at state entities, universities, and local governments",
    "restrictions": "Contract bans",
    "penalties": "Not specified",
    "summary": "The 'Hire Oklahomans Act' (Sen. Deevers, 2026 session) prohibits all Oklahoma state entities — agencies, universities, and local governments — from hiring or renewing employment of individuals under H-1B visas or Optional Practical Training (OPT) programs. Applies to new hires and contract renewals on or after July 1, 2026; does not affect existing employment agreements. First reading Feb 2, 2026; second reading referred to Senate Rules Feb 3, 2026; pending. Companion employer-focused bills: SB 1211 (H-1B-employer property tax exemption) and SB 1830 (job-creation payments).",
    "civilRightsImpact": "Nationality-neutral on its face, the bill would bar Oklahoma state entities from new H-1B or OPT hires of any nationality. Chinese nationals holding either status would be within that broader covered class. Existing employment agreements are unaffected. Pending in committee.",
    "keyProvisions": [
      "Prohibits state entities, universities, and local governments from hiring or renewing H-1B visa holders and OPT participants",
      "Applies to new hires and contract renewals on/after July 1, 2026",
      "Does not affect existing employment agreements",
      "Referred to Senate Rules Committee (Feb 3, 2026)"
    ],
    "url": "https://www.oklegislature.gov/BillInfo.aspx?Bill=sb2073&Session=2600",
    "officialUrl": "https://www.oklegislature.gov/cf_pdf/2025-26%20INT/SB/SB2073%20INT.PDF",
    "introducedDate": "2026-01-15",
    "lastUpdated": "2026-02-03"
  },
  {
    "id": "wa/property-SB 5057",
    "state": "WA",
    "stateName": "Washington",
    "billNumber": "SB 5057",
    "title": "Prohibiting PRC-government-associated nonresident aliens from acquiring agricultural, forest, and mineral land",
    "tier": 2,
    "status": "In Committee (Senate Law & Justice; reintroduced Jan 12, 2026)",
    "session": "69th Legislature (2025-2026)",
    "category": "property",
    "target": "Nonresident aliens associated with the government of the People's Republic of China, foreign businesses associated with the PRC government, and their agents, trustees, and fiduciaries (agricultural, forest, and mineral land; entities with 20%+ PRC-government ownership)",
    "restrictions": "Property restrictions",
    "penalties": "Not specified",
    "summary": "Would prohibit nonresident aliens connected to the PRC government, foreign businesses associated with the PRC government, and agents, trustees, or fiduciaries acting for them from acquiring agricultural, forest, or mineral land in Washington on or after August 1, 2025 (amends RCW 64.16.005 and adds a new section). Covers interests acquired directly or indirectly through entities, trusts, or fiduciaries, with a 20% PRC-government ownership threshold for covered entities. Prefiled December 16, 2024; read and referred to the Senate Law & Justice Committee January 13, 2025; reintroduced January 12, 2026.",
    "civilRightsImpact": "Restricts nonresident aliens with any PRC-government connection — including visa-holding Chinese nationals who are officers, employees, or funded by PRC government-linked entities — from acquiring agricultural, forest, or mineral land in Washington. Resident aliens (LPRs) and US citizens are not covered ('nonresident alien' excludes resident aliens).",
    "keyProvisions": [
      "China-specific: bars PRC-government-associated nonresident aliens, foreign businesses, agents, trustees, fiduciaries from acquiring agricultural/forest/mineral land",
      "Applies to acquisitions on or after Aug 1, 2025",
      "Covers indirect acquisition through entities, trusts, fiduciaries; 20% PRC-government ownership threshold for entities",
      "Prefiled 12/16/2024; referred to Law & Justice 1/13/2025; reintroduced 1/12/2026"
    ],
    "url": "https://app.leg.wa.gov/billsummary?BillNumber=5057&Year=2025&Initiative=false",
    "officialUrl": "https://lawfilesext.leg.wa.gov/biennium/2025-26/Pdf/Bills/Senate%20Bills/5057.pdf",
    "introducedDate": "2024-12-16",
    "lastUpdated": "2026-01-12"
  },
  {
    "id": "ct/property-HB 6735",
    "state": "CT",
    "stateName": "Connecticut",
    "billNumber": "HB 6735",
    "title": "Prohibiting foreign principals from acquiring interests in real property on or abutting military installations or agricultural land",
    "tier": 2,
    "status": "In Committee (Veterans' and Military Affairs; Joint Favorable Substitute; House calendar 2025; pending)",
    "session": "2025-2026",
    "category": "property",
    "target": "Foreign principals — governments, political parties, corporations, and individuals of foreign countries of concern (China, Russia) who are not US citizens or permanent residents — with respect to real property on or abutting military installations or agricultural land",
    "restrictions": "Property restrictions",
    "penalties": "Civil forfeiture and seizure; title vested in the state",
    "summary": "Would prohibit foreign principals from directly or indirectly owning, possessing, or acquiring interests in real property on or abutting military installations or agricultural land in Connecticut. Requires buyers of abutting property to sign an affidavit, under penalty of perjury, that they are not a foreign principal and to file it with the Adjutant General within one business day of closing. Requires foreign principals to notify the Adjutant General at least 30 days before purchasing property within three miles of a military installation; the Adjutant General reviews the transaction for public safety and may issue findings and a recommendation. Authorizes the Attorney General to bring civil forfeiture actions (with seizure in limited circumstances) and to vest title in the state, subject to bona fide lienholders; the state may then sell the property and distribute proceeds. Effective date would be October 1, 2025.",
    "civilRightsImpact": "Bars noncitizen, non-LPR individuals from China or Russia (the foreign countries of concern) from owning, possessing, or acquiring property on or abutting military installations or agricultural land, and subjects prospective purchases within three miles of a military installation to notice-and-review with forfeiture exposure. All buyers of affected property would have to submit an affidavit under penalty of perjury. LPRs and US citizens are exempt.",
    "keyProvisions": [
      "Prohibits foreign principals from owning/possessing/acquiring interests in property on or abutting military installations or agricultural land",
      "Affidavit of non-covered status for buyers of abutting property, filed with the Adjutant General within one business day",
      "30-day pre-purchase notice to the Adjutant General for purchases within 3 miles of a military installation",
      "Adjutant General public-safety review with written findings and recommendation",
      "AG civil forfeiture actions, limited seizure, and title vesting in the state",
      "Public hearing Feb 13, 2025; Joint Favorable Substitute Mar 2025; effective date Oct 1, 2025"
    ],
    "url": "https://www.cga.ct.gov/asp/cgabillstatus/cgabillstatus.asp?selBillType=Bill&bill_num=HB06735&which_year=2025",
    "officialUrl": "https://www.cga.ct.gov/2025/TOB/H/PDF/2025HB-06735-R02-HB.PDF",
    "introducedDate": "2025-01-09",
    "lastUpdated": "2026-08-17"
  },
  {
    "id": "nj/property-S 360",
    "state": "NJ",
    "stateName": "New Jersey",
    "billNumber": "S 360",
    "title": "Prohibiting sanctioned foreign governments and foreign persons from acquiring protected land adjacent to military facilities",
    "tier": 2,
    "status": "Introduced Jan 13, 2026; referred to Senate State Government, Wagering, Tourism & Historic Preservation",
    "session": "222nd Legislature (2026-2027)",
    "category": "property",
    "target": "Sanctioned foreign governments and their agents or fiduciaries, and foreign persons — noncitizens who are not 'alien friends' (R.S. 46:3-18) and are nonresident aliens, plus legal entities created under foreign law or majority-owned/controlled by foreign persons or foreign legal entities — acquiring protected land within 10 miles of military facilities",
    "restrictions": "Property restrictions",
    "penalties": "Not specified",
    "summary": "Would prohibit sanctioned foreign governments and certain foreign persons from acquiring any legal, beneficial, or other interest in 'protected land' — any parcel located within 10 miles of a federal military facility in New Jersey — on or after the effective date. Current owners may retain for up to five years of the effective date, then must convey to a non-covered person or entity; limited exceptions for acquisitions through debt collection, foreclosure, deed in lieu, and lien enforcement (2-year resale obligation) and by devise or descent or bona fide security encumbrances. A treaty clause makes the act inapplicable to a foreign government or foreign person of a country party to an inconsistent US treaty (relevant to reciprocal property-treaty nations). Effective immediately upon enactment.",
    "civilRightsImpact": "Would bar nonresident-alien Chinese nationals (and nationals of other states absent an applicable treaty) — including nonimmigrant visa holders — from acquiring property within 10 miles of New Jersey military facilities (Fort Dix/JB McGuire-Lakehurst, Picatinny Arsenal, Earle, etc.), with mandatory divestment within five years for existing holdings. Resident aliens (LPRs) and US citizens are excluded from the 'foreign person' definition, but LPRs could still be covered through the majority-ownership entity tests for foreign-government-linked persons.",
    "keyProvisions": [
      "Bars sanctioned foreign governments and foreign persons from acquiring interests in protected land within 10 miles of military facilities",
      "Foreign person includes nonresident aliens who are not 'alien friends' and entities majority-owned/controlled by foreign persons",
      "5-year divestment for pre-existing holdings; 2-year resale for debt-collection/foreclosure exceptions",
      "Devise/descent and bona fide security encumbrance exceptions",
      "US-treaty supremacy clause; effective immediately upon enactment",
      "Sponsored by Sens. Steinhardt and Tiver; prefiled for the 2026 session"
    ],
    "url": "https://www.njleg.state.nj.us/bill-search/2026/S360",
    "officialUrl": "https://pub.njleg.state.nj.us/Bills/2026/S0500/360_I1.PDF",
    "introducedDate": "2026-01-13",
    "lastUpdated": "2026-01-13"
  },
  {
    "id": "hi/property-SB 206",
    "state": "HI",
    "stateName": "Hawaii",
    "billNumber": "SB 206",
    "title": "Restrictions on nonresident alien ownership of real property (residential)",
    "tier": 2,
    "status": "Carried over to 2026; re-referred HOU/WLA and JDC Jan 21, 2026; no hearings scheduled",
    "session": "2025-2026",
    "category": "property",
    "target": "Nonresident aliens and businesses, trusts, or other entities significantly controlled by them (all real property, including residential; nationality-neutral)",
    "restrictions": "Property restrictions",
    "penalties": "Not specified",
    "summary": "Would restrict the purchase, ownership, or acquisition of real property interests in Hawaii by nonresident aliens and by foreign business entities and trusts significantly controlled by them, covering residential property in addition to agricultural and other land. The bill is nationality-neutral and applies to nationals of all countries who are not US citizens or resident aliens. Carried over from the 2025 session; re-referred to Housing/WLA and Judiciary & Hawaiian Affairs Committees January 21, 2026; no hearings scheduled.",
    "civilRightsImpact": "Would bar Chinese nationals who meet the bill's nonresident-alien definition, including covered visa holders and nonresident investors, from buying homes and other real property in Hawaii, including through entities or trusts they control. Resident aliens (LPRs) and US citizens are not covered. The legal classification is nationality-neutral; Chinese nationals are one group within the broader covered class.",
    "keyProvisions": [
      "Restricts nonresident aliens and significantly controlled entities/trusts from acquiring real property in Hawaii",
      "Covers all real property, including residential",
      "Nationality-neutral; carried over to 2026, re-referred Jan 21, 2026",
      "No hearings scheduled"
    ],
    "url": "https://data.capitol.hawaii.gov/session/measure_indiv.aspx?billtype=SB&billnumber=206&year=2025",
    "officialUrl": "https://data.capitol.hawaii.gov/sessions/session2025/bills/SB206_.HTM",
    "introducedDate": "2025-01-15",
    "lastUpdated": "2026-01-21"
  },
  // FAILED BILLS - Tier 2: affect visa holders, not residents (historical reference)
  {
    "id": "ia/contract-HF 2513",
    "state": "IA",
    "stateName": "Iowa",
    "billNumber": "HF 2513",
    "title": "Prohibiting institutions of higher education from entering employment contracts with H-1B visa holders from foreign adversaries",
    "tier": 2,
    "status": "Failed (Died in Senate)",
    "session": "91st General Assembly (2026)",
    "category": "contract",
    "target": "H-1B visa holders who are citizens of federally designated foreign adversaries (China, Russia, Iran) or state sponsors of terrorism (Venezuela, Cuba, North Korea, Syria)",
    "restrictions": "Contract bans",
    "penalties": "Not specified",
    "summary": "Passed the Iowa House 68-27 on March 3, 2026. Would have prohibited the three regents universities, community colleges, and other institutions of higher education (including private colleges) from entering employment contracts on or after July 1, 2026 with individuals holding a valid H-1B visa who are citizens of nations designated as foreign adversaries by the US Secretary of Commerce or state sponsors of terrorism by the US Secretary of State. The Senate never brought the bill to a floor vote (unfinished business as of March 26, 2026) and it died at adjournment. An earlier version (HSB 536) covered Chinese citizens only; the amended bill covers all designated countries.",
    "civilRightsImpact": "Would have barred covered Iowa colleges and universities from hiring Chinese nationals and other designated-country nationals on H-1B visas, including faculty, researchers, and staff. US citizens and lawful permanent residents are not affected because they do not hold H-1B visas. The bill passed the House and did not receive a Senate floor vote before adjournment.",
    "keyProvisions": [
      "Bans employment contracts with H-1B holders who are citizens of foreign adversaries or state sponsors of terrorism",
      "Applies to regents institutions, community colleges, and other institutions of higher education (including private)",
      "Effective date would have been July 1, 2026",
      "Passed House 68-27 (March 3, 2026); died in the Senate without a floor vote"
    ],
    "url": "https://www.legis.iowa.gov/legislation/billTracking/billHistory?billName=HF2513&ga=91",
    "officialUrl": "https://www.legis.iowa.gov/docs/publications/LGR/91/HF2513.pdf",
    "introducedDate": "2026-01-13",
    "lastUpdated": "2026-03-26"
  },
  {
    "id": "mo/contract-SB 1130",
    "state": "MO",
    "stateName": "Missouri",
    "billNumber": "SB 1130",
    "title": "Prohibiting state colleges and universities from employing H-1B visa holders",
    "tier": 2,
    "status": "Failed (Hearing Cancelled)",
    "session": "2026",
    "category": "contract",
    "target": "All H-1B visa holders (nationality-neutral — affects Chinese nationals among others) at state colleges and universities and their contractors",
    "restrictions": "Contract bans",
    "penalties": "Not specified",
    "summary": "Introduced by Sen. Carter (2026 session). Would have prohibited any state college or university — any public community college, college, or university in Missouri — from employing any individual who possesses an H-1B visa, and from entering into contracts with, or otherwise engaging the services of, any contractor owned by or employing an H-1B visa holder. The Senate Education Committee hearing was cancelled (Feb 23-24, 2026) and the bill died without further action. Universities projected major fiscal impacts (over $1M for the University of Missouri System).",
    "civilRightsImpact": "Nationality-neutral on its face, the bill would have barred H-1B hiring at Missouri public colleges regardless of country. Chinese nationals holding H-1B status would have been within that broader covered class. Unlike Iowa's HF 2513, coverage was not tied to a national-security country list. Failed to advance.",
    "keyProvisions": [
      "Prohibits state colleges and universities from employing any H-1B visa holder",
      "Prohibits contracting with companies owned by or employing H-1B visa holders",
      "Rulemaking authority for the Department of Higher Education and Workforce Development",
      "Education committee hearing cancelled (Feb 2026); did not advance"
    ],
    "url": "https://www.senate.mo.gov/BillTracking/Bills/BillInformation?billid=224&year=2026",
    "officialUrl": "https://www.senate.mo.gov/26info/pdf-bill/intro/SB1130.pdf",
    "introducedDate": "2026-01-07",
    "lastUpdated": "2026-05-15"
  },
  {
    "id": "in/education-HB 1099",
    "state": "IN",
    "stateName": "Indiana",
    "billNumber": "HB 1099",
    "title": "Foreign adversaries (foreign-student screening, tech contracts, real property)",
    "tier": 2,
    "status": "Failed (Died in Senate)",
    "session": "2026",
    "category": "education",
    "target": "Foreign students who are citizens of foreign adversaries (China, Russia, North Korea, Iran) and not US citizens, lawful permanent residents, or asylees, in qualifying STEM programs",
    "restrictions": "Educational restrictions; property restrictions (agents of foreign adversaries)",
    "penalties": "Denial of admission, unenrollment; $10,000 civil penalty (real property)",
    "summary": "Passed the Indiana House 74-22 (Feb 2, 2026) but died in the Senate (Committee on Homeland Security and Transportation). Would have required state educational institutions, beginning August 15, 2026, to complete a 'foreign influence and research security review' before admitting a foreign student into qualifying programs (chemical, electrical, industrial, and mechanical engineering; artificial intelligence; computer science; microbiology; virology) — reviewing affiliations, outside funding, agreements, and whether the student, parents, siblings, spouse, grandparents, aunts, or uncles are government employees, political party members, or members of united front organizations of a foreign adversary. Institutions could not admit students found to be agents of a foreign adversary or who refused to provide information, and must unenroll students who accept foreign-adversary funding. Also prohibited 'prohibited persons' (agents of foreign adversaries) from acquiring Indiana real property, with attorney general enforcement and a $10,000 civil penalty.",
    "civilRightsImpact": "Applies to citizens of foreign adversaries (including China) who are not US citizens, LPRs, or asylees — including F-1 and J-1 students — and requires screening of students and relatives, including political-party membership questions. Refusal to cooperate can result in denial of admission, and covered foreign-adversary funding can require unenrollment. LPRs and asylees are exempt from the student provisions. The real-property provisions apply only to persons found to be acting as agents of a foreign adversary (conduct-based, not nationality-based).",
    "keyProvisions": [
      "Foreign influence and research security review before admitting foreign students to qualifying STEM programs (Aug 15, 2026)",
      "Review of affiliations, foreign funding, and family ties to adversary governments, political parties, and united front organizations",
      "Bar on admitting agents of foreign adversaries or students who refuse to provide information",
      "Attestation against foreign-adversary funding; immediate unenrollment on violation",
      "Real-property ban and $10,000 civil penalty for prohibited persons",
      "Passed House 74-22; died in Senate committee"
    ],
    "url": "https://iga.in.gov/legislative/2026/bills/house/1099/details",
    "officialUrl": "https://iga.in.gov/legislative/2026/bills/house/1099/details",
    "introducedDate": "2026-01-07",
    "lastUpdated": "2026-02-16"
  },
  // FAILED BILLS - Tier 1: affect LPRs/US citizens (historical reference)
  {
    "id": "az/property-HB 2171",
    "state": "AZ",
    "stateName": "Arizona",
    "billNumber": "HB 2171",
    "title": "Prohibiting real-property ownership or leases by hostile entities and former foreign military personnel",
    "tier": 1,
    "status": "Failed (Held in Senate after House approval)",
    "session": "57th Legislature, 2nd Regular Session (2026)",
    "category": "property",
    "target": "China-, Iran-, North Korea-, and Russia-controlled entities and any individual who served in the military of one of those countries; no US-citizen or LPR exemption",
    "restrictions": "Property restrictions",
    "penalties": "One-year disposal; state takeover and auction; public prohibited-owner list; Class 4 felony",
    "summary": "HB 2171 would have prohibited the sale, lease, or conveyance of Arizona real property to listed hostile entities or to any individual who served in the military of China, Iran, North Korea, or Russia. Existing and newly acquired interests would have to be disposed of within one year; otherwise the Department of Administration would take and auction the interest. The Department of Public Safety would investigate and publish a prohibited-owner list.",
    "civilRightsImpact": "The former-military clause contains no citizenship, lawful-permanent-resident, age, time, or service-type limitation. A naturalized US citizen or LPR of Chinese origin who previously served in the PLA could have been prohibited from owning or leasing any Arizona real property, publicly listed, deprived of the interest through state auction, and prosecuted for a felony for knowingly acquiring it.",
    "keyProvisions": [
      "Covers any individual who served in the military of China, Iran, North Korea, or Russia",
      "No US-citizen or lawful-permanent-resident exemption",
      "Prohibits sale, lease, or conveyance of any Arizona real-property interest",
      "One-year disposal requirement followed by state takeover and public auction",
      "DPS investigation and public prohibited-owner list; Class 4 felony",
      "Passed the House but was held in the Senate"
    ],
    "url": "https://apps.azleg.gov/BillStatus/BillOverview/83833?SessionId=130",
    "officialUrl": "https://www.azleg.gov/legtext/57leg/2R/bills/HB2171P.pdf",
    "introducedDate": "2026-01-08",
    "lastUpdated": "2026-06-30"
  },
  {
    "id": "nh/property-SB 162",
    "state": "NH",
    "stateName": "New Hampshire",
    "billNumber": "SB 162-FN",
    "title": "Foreign-principal real-property restrictions near protected military facilities",
    "tier": 1,
    "status": "Failed (House: Inexpedient to Legislate)",
    "session": "2025-2026",
    "category": "property",
    "target": "Governments, officials, companies, and natural-person employees or agents of China, Russia, Iran, Syria, and North Korea; no US-citizen or LPR exemption",
    "restrictions": "Property restrictions",
    "penalties": "$500 affidavit penalty; Class A misdemeanor for a natural person; seizure and civil forfeiture",
    "summary": "As amended by the Senate, SB 162-FN would have prohibited a foreign principal from acquiring, leasing, occupying, or controlling real property within 10 miles of specified New Hampshire National Guard and military facilities. A foreign principal included any natural person who is an employee or agent of China, Russia, Iran, Syria, or North Korea. Every purchaser or lessee in the covered area would have had to file a notarized eligibility affidavit.",
    "civilRightsImpact": "The natural-person definition contains no exemption for US citizens or lawful permanent residents. A Chinese American citizen or LPR deemed an employee or agent of the PRC could have been denied property ownership or a lease near protected facilities and exposed to a misdemeanor, seizure, and forfeiture. The House recommended the bill inexpedient to legislate after it passed the Senate with amendment.",
    "keyProvisions": [
      "10-mile ownership, lease, occupancy, and control ban around protected military facilities",
      "Foreign principal includes natural-person employees or agents of China and four other countries",
      "No US-citizen or LPR exemption for covered individuals",
      "Notarized purchaser/lessee affidavit required for every covered transaction",
      "$500 filing penalty, Class A misdemeanor for natural persons, and civil forfeiture",
      "Passed the Senate with amendment; House found it inexpedient to legislate"
    ],
    "url": "https://gc.nh.gov/bill_status/billinfo.aspx?id=1054&inflect=2",
    "officialUrl": "https://gc.nh.gov/bill_Status/pdf.aspx?id=10959&q=billVersion",
    "introducedDate": "2025-01-09",
    "lastUpdated": "2025-10-28"
  },
  {
    "id": "ak/property-SB 139",
    "state": "AK",
    "stateName": "Alaska",
    "billNumber": "SB 139",
    "title": "Alaska Critical Infrastructure and Land Ownership Act (restrictions near military installations and on agricultural land)",
    "tier": 1,
    "status": "Failed (Did not advance)",
    "session": "34th Legislature (2025-2026)",
    "category": "property",
    "target": "Citizens of China, Iran, North Korea, and Russia (land within 100 miles of military installations); citizens of foreign adversaries and their entities (agricultural land). Only US citizens exempt — lawful permanent residents are NOT exempt",
    "restrictions": "Property restrictions",
    "penalties": "Forfeiture of land interests",
    "summary": "The 'Alaska Critical Infrastructure and Land Ownership Act' (Sen. Hughes, 34th Legislature) would have prohibited a citizen of China, Iran, North Korea, or Russia — or a company prohibited from critical infrastructure agreements — from purchasing, leasing, or otherwise acquiring land within 100 miles of a military installation, and barred citizens of US-designated foreign adversaries and their entities from acquiring or leasing agricultural land. Enforcement via attorney general forfeiture actions. Exempts US citizens who are also citizens of a listed country and residential property leases. Bill hearing cancelled (April 2025); did not advance.",
    "civilRightsImpact": "The exemption covers only US citizens. Lawful permanent residents who are citizens of China or another listed country would have been barred from agricultural land and land within 100 miles of a military installation, and could have faced forfeiture of interests held in violation. Failed to advance in the 2025-2026 session.",
    "keyProvisions": [
      "Bans citizens of China, Iran, North Korea, and Russia from acquiring or leasing land within 100 miles of military installations",
      "Bans foreign-adversary citizens and entities from acquiring or leasing agricultural land",
      "Only US citizens exempt — LPRs not exempt; residential leases exempt",
      "Attorney general forfeiture enforcement",
      "Hearing cancelled April 2025; did not advance"
    ],
    "url": "https://www.akleg.gov/basis/Bill/Detail/34?Root=SB+139",
    "officialUrl": "https://www.akleg.gov/basis/Bill/Text/34?Hsid=SB0139A",
    "introducedDate": "2025-03-19",
    "lastUpdated": "2025-04-14"
  },
  // FAILED BILLS - Tier 1: affect LPRs/US citizens (historical reference)
  {
    "id": "nh/government-HB 1606",
    "state": "NH",
    "stateName": "New Hampshire",
    "billNumber": "HB 1606",
    "title": "Regulating real property ownership by Chinese nationals",
    "tier": 1,
    "status": "Inexpedient to Legislate",
    "session": "2026",
    "category": "property",
    "target": "Chinese nationals",
    "restrictions": "Property restrictions",
    "penalties": "Civil, criminal, and administrative penalties",
    "summary": "Regulates real property ownership by Chinese nationals and provides for civil, criminal, and administrative penalties.",
    "civilRightsImpact": "The proposal expressly classified people by Chinese nationality and would have attached civil, criminal, and administrative consequences to covered property ownership. The House subsequently deemed the bill inexpedient to legislate.",
    "keyProvisions": [
      "Regulates Chinese national property ownership",
      "Includes civil, criminal, and administrative penalties"
    ],
    "url": "https://gc.nh.gov/bill_status/billinfo.aspx?id=1595&inflect=2",
    "officialUrl": "https://gc.nh.gov/bill_status/pdf.aspx?id=23983&q=billVersion",
    "introducedDate": "2026-01-07",
    "lastUpdated": "2026-02-19"
  },
  {
    "id": "nh/government-HB 1561",
    "state": "NH",
    "stateName": "New Hampshire",
    "billNumber": "HB 1561",
    "title": "Prohibiting PRC nationals from graduate enrollment, research, and full-time employment at public colleges",
    "tier": 1,
    "status": "Inexpedient to Legislate",
    "session": "2026",
    "category": "education",
    "target": "PRC nationals who are not US citizens, including lawful permanent residents and visa holders; PRC-government-affiliated entities",
    "restrictions": "Graduate enrollment, research participation, and full-time employment restrictions",
    "penalties": "Expulsion or termination, Class A misdemeanors, institutional fines and funding/accreditation consequences, federal immigration referral",
    "summary": "As amended by the House, would have prohibited PRC nationals who are not US citizens from enrolling in master's or doctorate programs, participating in research, or holding full-time employment at New Hampshire public colleges and universities. It also barred institutional partnerships, grants, and research collaborations with PRC-government-affiliated entities.",
    "civilRightsImpact": "Would have excluded people from graduate education, research, and public-college employment based on PRC nationality. US citizens were exempt, but lawful permanent residents and visa holders were not. Covered individuals already enrolled or employed would have had 90 days to withdraw, followed by mandatory expulsion, Class A misdemeanor exposure, and possible referral for visa revocation or deportation. Institutions and faculty also faced financial or criminal penalties, and informants could receive 10 percent of recovered funds.",
    "keyProvisions": [
      "Bars covered PRC nationals from master's and doctorate programs, research, and full-time employment at public institutions",
      "US citizens are exempt; lawful permanent residents are not exempt",
      "Requires covered students and employees to withdraw within 90 days",
      "Creates Class A misdemeanor penalties and possible immigration referrals",
      "Allows institutional fines, loss of funding or accreditation consequences, and a 10 percent informant award"
    ],
    "url": "https://gc.nh.gov/bill_status/billinfo.aspx?id=1549&inflect=2",
    "officialUrl": "https://gc.nh.gov/bill_status/pdf.aspx?id=28739&q=billVersion",
    "introducedDate": "2026-01-07",
    "lastUpdated": "2026-03-11"
  }
];

// Category mappings
const categoryNames = {
    "property": "Property Restrictions",
    "education": "Educational Discrimination",
    "contract": "Contract Bans",
    "financial": "Financial Restrictions",
    "infrastructure": "Infrastructure Bans",
    "other": "Other Restrictions"
};

// State mappings
const stateNames = {
    "FL": "Florida",
    "TX": "Texas",
    "AL": "Alabama",
    "ID": "Idaho",
    "AR": "Arkansas",
    "AZ": "Arizona",
    "CT": "Connecticut",
    "HI": "Hawaii",
    "IN": "Indiana",
    "KS": "Kansas",
    "LA": "Louisiana",
    "NJ": "New Jersey",
    "TN": "Tennessee",
    "WA": "Washington",
    "NH": "New Hampshire",
    "NY": "New York",
    "OK": "Oklahoma",
    "IA": "Iowa",
    "MO": "Missouri",
    "NE": "Nebraska",
    "AK": "Alaska"
};
